name: A workflow for my Hello World file
on: push
jobs:
  first_job:
    name: Build TVM
    runs-on: ubuntu-latest
    steps:
      - name: Build
        shell: bash -l {0}
        run: |
            pwd
            

