name: A workflow for my Hello World file
on: push
jobs:
  first_job:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: show event
        run: |
            echo "test ${{ github.event_name }}"
            echo run number is $GITHUB_RUN_NUMBER
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.2.0
        with:
          NAME: test
          LABEL: 'abc'
          STATUS: 'pass'
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
