name: Pypi Release

on:
  release:
    types: [created]

permissions:
  id-token: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo im on master "${{ github.ref }}"


