name: 'build-test'
on: [pull_request, push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          python3 -c "import os; os.environ['abc']='123'"
          echo $abc
      - name: test
        if: ${{ github.ref == yinweisu/hello-github-actions && (github.event_name == 'pull_request' || github.event_name == 'push') }}
        run: |
          echo hi
      - name: Execute if the job was cancelled
        if: ${{ cancelled() }}
        run: echo cancelled

