name: A workflow for my Hello World file
on: push
jobs:
  first_job:
    name: Build TVM
    runs-on: ubuntu-latest

    steps:
      - name: Build
        shell: bash -l {0}
        run: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-dev python3-setuptools gcc libtinfo-dev zlib1g-dev build-essential cmake libedit-dev libxml2-dev
            wget -O - https://apt.llvm.org/llvm.sh
            git clone --recursive https://github.com/apache/tvm tvm
            cd tvm
            mkdir build
            cp cmake/config.cmake build
            cd build
            cmake -DUSE_LLVM=ON ..
            make -j4

