name: 'build-test'
on: [pull_request, push]

permissions:
  id-token: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo hi "${{ github.ref }}"


