name: Cloud Continuous Integration

on:
  pull_request_target:
   types: [labeled, synchronize]
   

permissions:
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  permission_check:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo '${{ github.event.pull_request.head.ref }}'
