name: 'build-test'
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          short_sha=$(git rev-parse --short "$GITHUB_SHA")
          echo "SHORT_SHA=$short_sha" >> $GITHUB_ENV
      - run: echo ${{ env.SHORT_SHA }}
