name: A workflow for my Hello World file
on: push
jobs:
  first_job:
    name: Build TVM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TVM
        run: |
            git clone --recursive https://github.com/apache/tvm tvm
