name: A workflow for my Hello World file
on: push
jobs:
  first_job:
    name: Build TVM
    runs-on: ubuntu-latest

    steps:
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: 3.7
      - name: Build
        shell: bash -l {0}
        run: |
            conda env create --file conda/build-environment.yaml
            conda activate tvm-build
            git clone --recursive https://github.com/apache/tvm tvm
            cd tvm
            mkdir build
            cp cmake/config.cmake build
            cd build
            cmake ..
            make -j4

