name: 'build-test'
on: [pull_request, push]

permissions:
  id-token: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::377786338321:role/test_oidc
          aws-region: us-east-1
      - run: |
          aws s3 ls


