name: 'build-test'
on: [pull_request, push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sleep 60
      - name: Execute if the job was cancelled
        if: ${{ cancelled() }}
        run: echo cancelled
